language: node_js
node_js:
  - "12.4.0"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli@7.3.9
script:
  - ng lint
  - ng build --prod --base-href https://openmf.github.io/online-banking-app/
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: ./dist/online-banking-app
  github_token: $GIT_TOKEN
  on:
    branch: master
env:
  global:
    - secure: qou4asfmdzzcv010+z7Syazm2A6rsQOoJDwHC5joq5OL14m8XrV2/nY1jntexAa0wUfeFhQDAOicvP1sh/fZNi65Pe3Wtr7CtXP4YF650Ri1xukj2IAK5MbrwQQU9YwTb+LB7sZe4u4b/wvQ7e0mxQhuQ8ua82Ouxmgpt0paHMZC69NomefXbzugA9v3Ddp6m5KYxcpgByuNT4EkDeKQtoZJwuBWni3Iy8Ik5uCJUpAHoj9F3OFQCxh+jMHzekv65BqA35UA9AeuQR/Kl+zNaKgVUsU2I5PVOpWsX+Vp9rZb1JZPpkeUGSdsmqxbmCDLB9LOs7sz+j9yz+vir9bA39i2edZheSFyMH2HdlHne5dD1P04ODrxro0/rmaC2y2SFKt1KrN0JqK54/YVIEzNKwpJrVp0yEmP4QwC5T6KKy7pvwBe1PerYutbeKLGc9bVDabVFO9qbUUPAJHjgh02+NGAQDuRVNL0TQo10F/Y4JrtZ0kIR00rrYjmlfrOMJedJ/9fs/4LmgtDheCX0yS3B6Lgv6o6XWkokurd+UYfHV1wlbtwTwbMbp8/Sjk8czC3ax4r/2a+NmOXuYG+Bmllp6r9XvCm1JtFifnw46cY/RdkDb62OgGgmAlRc1DoW6nSYlGPkQfNnjKI0LzqCmi7XiHxv/XkZiV8/El7dIcqJ4Y=
